### ISSUE TITLE
Doubts and problems when installing syncap

### ISSUE THREAD

**Issue by MinionAttack** [e-bug/syncap#1]
Hi, I wanted to try this tool but I'm having some problems in the installation of this tool.

The first problem is that `en-core-web-sm==2.1.0` is not available via PIP, so the command `conda env create -f environment.yml` fails. 

To fix it I had to remove the line `en-core-web-sm==2.1.0` from the PIP dependencies section, run the command again and when it finishes installing everything correctly install `en-core-web-sm==2.1.0` manually with this command:

`path-to-anaconda3/envs/syncap/bin/pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.1.0/en_core_web_sm-2.1.0.tar.gz#egg=en_core_web_sm==2.1.0`

Then I was trying to execute `bash setup_environment.sh` and because now you have to use `conda activate` instead of `source activate` I have modified the line 6 from `source activate syncap` to `conda activate syncap` but I get an error:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

To solve this, after doing `conda env create -f environment.yml` and installing manually `en_core_web_sm==2.1.0
` close the terminal, open it again in the same folder and type `conda activate syncap`. Now open the file `setup_environment.sh` and comment lines 6 and 36. Execute `bash setup_environment.sh` and it works.

Now I'm stuck with `Finally, install the environments for M2-Transformer and Improved BERTScore to use them.`. **I do not know if they are needed to train a model** but if I try to run `conda env create -f environment.yml` inside `code/meshed-memory-transformer` I get:

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - openssl==1.1.1=h7b6447c_0
  - mkl==2019.5=281
  - intel-openmp==2019.5=281

```
Also, with _Improved BERTScore_ dependencies must be installed in a virtual environment specific to _Improved BERTScore_ or globally? But the _README.md_ says `bert_score==0.1.2 (already in this repo)` so it can be skipped or I have to install the 3 dependencies?

Yours faithfully.

**Comment by e-bug** [comment]
Thanks for the comments on setting up the repo!

Yes, I'll remove `en-core-web-sm==2.1.0` from the required packages and say that it needs to be installed later.

I interchangeably use `conda activate` and `source activate` depending on the system I use.
But thanks for explaining how you made it work! It will be helpful to others :)

If you want to use M2-Transformer, then you need to install its packages.
You can safely remove those three from the requirements (I'll do it here too).

As for BERTScore, I installed it in its own environment.
If you check its requirements, they do not include `bert_score==0.1.2`. 
So you can just set up the environment as you have done earlier.

**Comment by MinionAttack** [comment]
Hi, I have removed those libraries in the _M2-Transformer_ _environment.yml_ file and the installation is complete.

For _BERTScore_, I have created a virtual environment for it alone and installed the entire requirements.txt file.

Is this the right way?

**Comment by e-bug** [comment]
Yes! Feel free to send a Pull Request with your changes so others can benefit from your fixes.
